### ISSUE TITLE
Referee Creation Page - Rules url only accepts host name urls

### ISSUE THREAD

**Issue by huntpbrennan** [PastyPurpleTrolls/game-contest-server#26] opened 2017-01-03 16:46 UTC
It does not allow for any paths on urls

**Comment by McSkivv** [comment] 2017-01-04 14:59
Cannot reproduce on Master.  Please give more detailed information.

**Comment by McSkivv** [comment] 2017-01-20 16:24
Still cannot reproduce.  Given no additional information, closing the issue.

**Closed by McSkivv** 2017-01-20 16:24 UTC
Labels: bug
